version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      actions-major:
        update-types:
          - "major"
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      npm-major:
        update-types:
          - "major"
        patterns:
          - "*"