---
name: "Bug report"
description: "Report a reproducible problem"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: "Validation"
      options:
        - label: "I have searched existing issues to avoid duplicates"
          required: true
  - type: textarea
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "How can we reproduce the behavior?"
      placeholder: "1. Go to ... 2. Click ... 3. See error"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Screenshots or logs"
      description: "If applicable, add screenshots or logs to help explain your problem."
  - type: input
    attributes:
      label: "App version / commit"
      description: "Version number or commit SHA if relevant"