name: Bug report
description: Reporte um problema encontrado
title: "[BUG] Descreva o problema"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: Descreva claramente o problema.
      placeholder: O que aconteceu?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Liste os passos para reproduzir o bug.
      placeholder: |
        1. Vá para '...'
        2. Clique em '...'
        3. Veja o erro
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
      placeholder: O que você esperava que acontecesse?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots ou logs
      description: Cole logs e/ou adicione imagens se possível.
      render: shell
  - type: input
    id: version
    attributes:
      label: Versão/Commit
      placeholder: vX.Y.Z ou SHA
  - type: input
    id: env
    attributes:
      label: Ambiente
      placeholder: SO, navegador, etc.
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: Verifiquei se já existe issue semelhante.
          required: true