name: Auto-approve Dependabot PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited, labeled]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Auto-approve Dependabot PR
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Auto-approve the PR
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            });

            const prNumber = context.payload.pull_request.number;
            console.log('Auto-approved Dependabot PR #' + prNumber);