name: Auto-merge Dependabot PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited, labeled]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Enable auto-merge for minor, patch, and security updates
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'security' }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash