name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Steps below only run if a Node.js project is detected
      - name: Setup Node.js
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        if: hashFiles('package.json') != ''
        run: npm ci

      - name: Lint (if present)
        if: hashFiles('package.json') != ''
        run: npm run lint --if-present

      - name: Test (if present)
        if: hashFiles('package.json') != ''
        run: npm test --if-present

      - name: Build (if present)
        if: hashFiles('package.json') != ''
        run: npm run build --if-present

      # Keep pipeline neutral in non-Node repos
      - name: Finalize
        if: hashFiles('package.json') == ''
        run: echo "Basic CI executed (no specific stack detected)."